#!/bin/bash
# Wait for radio.liq to be generated by Node.js, or use template as fallback

MAX_WAIT=15
WAITED=0

while [ ! -f /app/radio.liq ] && [ $WAITED -lt $MAX_WAIT ]; do
    echo "Waiting for radio.liq to be generated... ($WAITED/$MAX_WAIT)"
    sleep 1
    WAITED=$((WAITED + 1))
done

# If still no radio.liq, copy template as fallback
if [ ! -f /app/radio.liq ]; then
    echo "No radio.liq found, using template"
    cp /app/radio.liq.template /app/radio.liq
fi

exec /usr/bin/liquidsoap /app/radio.liq
